### ISSUE TITLE
Replacing the node-html-parser by Cheerio

### ISSUE THREAD

**Issue by NemesisX1** [NemesisX1/canal_olympia_scrapping_api#10]
I guess it will be more suitable to move from node-html-parser to Cheerio which more mainstream. Feel free to pick this issues and submit a pull request about that. 

Currently there is only the theatersNames() function which is using Cheerio. Thank to @abstractHunter for his pull request about that.

**Comment by abstractHunter** [comment]
Okay, I also think so.
I am taking this issue and I will submit a PR soon.
